# Generated by Django 4.2.6 on 2024-01-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'default'), (1, 'sport'), (2, 'health')], default=0)),
                ('describe', models.TextField()),
                ('kcal', models.IntegerField()),
                ('proteins', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fats', models.FloatField()),
                ('fluids', models.IntegerField()),
            ],
        ),
    ]
