# Generated by Django 4.2.6 on 2024-01-16 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
        ('diets', '0002_remove_diet_kind_diet_fiber'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='user_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_messages.usermessage'),
        ),
    ]
