# Generated by Django 4.2.6 on 2024-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_diet_user_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='fiber',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='fluids',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='kcal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diet',
            name='proteins',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
