# Generated by Django 4.2.6 on 2024-01-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_alter_diet_carbohydrates_alter_diet_describe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='fluids',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
