# Generated by Django 4.2.6 on 2023-11-14 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paremeters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('physic_activity', models.IntegerField(choices=[(0, 'not define'), (1, 'brak aktywnosci fizycznej'), (2, 'mala aktywnosc fizyczna'), (3, 'umiarkowana aktywnosc fizyczna'), (4, 'duza aktywnosc fizyczna'), (5, 'codzienna aktywnosc fizyczna')], default=0)),
                ('chest', models.FloatField()),
                ('belly', models.FloatField()),
                ('biceps', models.FloatField()),
                ('arms', models.FloatField()),
                ('thighs', models.FloatField()),
                ('calves', models.FloatField()),
            ],
        ),
    ]
