# Generated by Django 4.2.6 on 2023-12-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paremeters',
            new_name='Parameters',
        ),
    ]
