# Generated by Django 4.2.6 on 2023-12-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_rename_paremeters_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='user_id',
        ),
    ]
