# Generated by Django 4.2.6 on 2023-12-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0004_parameters_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='bmi',
            field=models.FloatField(null=True),
        ),
    ]
