# Generated by Django 4.2.6 on 2024-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0007_alter_parameters_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='age',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameters',
            name='sex',
            field=models.IntegerField(choices=[(0, 'not define'), (1, 'man'), (2, 'women')], default=0),
        ),
    ]
