# Generated by Django 4.2.6 on 2024-01-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0008_parameters_age_parameters_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='age',
        ),
    ]
