# Generated by Django 4.2.6 on 2024-01-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fiber',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
