# Generated by Django 4.2.6 on 2024-01-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiry_date',
        ),
    ]
