# Generated by Django 4.2.6 on 2024-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
