# Generated by Django 4.2.6 on 2024-03-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0007_alter_usermessage_allergies_and_more'),
        ('orders', '0006_order_expiry_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_message_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_messages.usermessage'),
        ),
    ]
