# Generated by Django 4.2.6 on 2024-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_user_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diet_type',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
