# Generated by Django 4.2.6 on 2023-12-02 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0003_remove_parameters_user_id'),
        ('users', '0006_remove_user_parameters_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parameters_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parameters.parameters'),
        ),
    ]
