# Generated by Django 4.2.6 on 2024-01-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='allergies',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='eating',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessage',
            name='health_problems',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
