# Generated by Django 4.2.6 on 2024-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_usermessage_allergies_usermessage_eating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='target',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
