# Generated by Django 4.2.6 on 2024-03-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0003_usermessage_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='allergies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='health_problems',
            field=models.TextField(blank=True, null=True),
        ),
    ]
