# Generated by Django 4.2.6 on 2024-03-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0004_alter_usermessage_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='allergies',
            field=models.TextField(default=''),
        ),
    ]
