# Generated by Django 4.2.6 on 2024-03-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0005_alter_usermessage_allergies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='allergies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='health_problems',
            field=models.TextField(default=4),
            preserve_default=False,
        ),
    ]
