# Generated by Django 4.2.6 on 2024-01-17 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diets', '0005_alter_diet_fluids'),
        ('products', '0003_product_fiber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('product1_weight', models.IntegerField()),
                ('product2_weight', models.IntegerField()),
                ('product3_weight', models.IntegerField()),
                ('product4_weight', models.IntegerField()),
                ('product5_weight', models.IntegerField()),
                ('product6_weight', models.IntegerField()),
                ('product7_weight', models.IntegerField()),
                ('product8_weight', models.IntegerField()),
                ('product9_weight', models.IntegerField()),
                ('product10_weight', models.IntegerField()),
                ('product11_weight', models.IntegerField()),
                ('product12_weight', models.IntegerField()),
                ('diet_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diets.diet')),
                ('product10_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product10', to='products.product')),
                ('product11_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product11', to='products.product')),
                ('product12_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product12', to='products.product')),
                ('product1_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product1', to='products.product')),
                ('product2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product2', to='products.product')),
                ('product3_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product3', to='products.product')),
                ('product4_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product4', to='products.product')),
                ('product5_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product5', to='products.product')),
                ('product6_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product6', to='products.product')),
                ('product7_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product7', to='products.product')),
                ('product8_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product8', to='products.product')),
                ('product9_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dietmeal_product9', to='products.product')),
            ],
        ),
    ]
