# Generated by Django 4.2.6 on 2024-01-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietmeal',
            name='product10_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product11_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product12_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product1_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product2_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product3_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product4_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product5_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product6_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product7_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product8_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='product9_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
