# Generated by Django 4.2.6 on 2024-04-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_meals', '0002_alter_dietmeal_product10_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietmeal',
            name='meal',
            field=models.CharField(choices=[('I POSIŁEK', 'FIRST MEAL'), ('II POSIŁEK', 'SECOND MEAL'), ('III POSIŁEK', 'THIRD MEAL'), ('IV POSIŁEK', 'FOURTH MEAL'), ('V POSIŁEK', 'FIFTH MEAL'), ('VI POSIŁEK', 'SIXTH MEAL')]),
        ),
    ]
